# -*- coding: utf-8 -*-
"""ML model.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1aDkKZK_xLIsSWk1n_hYyLGOMKwDpH2xL
"""

import pandas as pd
import numpy as np
from sklearn.model_selection import train_test_split, cross_val_score, KFold
from sklearn.ensemble import RandomForestRegressor
from sklearn.preprocessing import OneHotEncoder
from sklearn.compose import ColumnTransformer
from sklearn.pipeline import Pipeline
from sklearn.metrics import r2_score, mean_squared_error, mean_absolute_error

df = pd.read_excel('/content/barley (2).xlsx')
display(df.head())

df.info()

# Check for missing values
missing_values = df.isnull().sum()
display(missing_values[missing_values > 0].sort_values(ascending=False))

#  Convert string column(s) to float

df = df.replace(".", np.nan)
df["GY"] = pd.to_numeric(df["GY"], errors="coerce")
df["BY"] = pd.to_numeric(df["BY"], errors="coerce")

# Drop the handful of rows with missing target/feature values
df = df.dropna(subset=["GY", "BY"])

print(f"Dataset shape after cleaning: {df.shape}")

import matplotlib.pyplot as plt
import seaborn as sns

#1. Boxplot of GY across Nutrient types - see which nutrient gives higher yield
plt.figure(figsize=(8, 5))
sns.boxplot(x='Nutrient', y='GY', data=df)
plt.title('Grain Yield (GY) by Nutrient Type')
plt.show()

# 2. Histograms - distribution shape of each numeric variable
plt.figure(figsize=(15, 4))
numerical_cols = ['Rep', 'Rate', 'GY', 'BY']
for i, col in enumerate(numerical_cols):
    plt.subplot(1, 4, i + 1)
    sns.histplot(df[col], kde=True, bins=30)
    plt.title(f'Distribution of {col}')
plt.tight_layout()
plt.show()

# 3. Countplot  → whether your data is balanced across the 13 locations
plt.figure(figsize=(12, 5))
sns.countplot(x='Location', data=df, order=df['Location'].value_counts().index)
plt.xticks(rotation=45)
plt.title('Number of Records per Location')
plt.tight_layout()
plt.show()

# 4. Scatter plot → whether higher nutrient rate is associated with higher yield
plt.figure(figsize=(7, 5))
sns.scatterplot(x='Rate', y='GY', hue='Nutrient', data=df)
plt.title('GY vs Rate, colored by Nutrient')
plt.show()

# 6. Correlation heatmap → strength of linear relationship between GY, BY, and Rate
numerical_cols = ['Rep', 'Rate', 'GY', 'BY']
plt.figure(figsize=(5, 4))
sns.heatmap(df[numerical_cols].corr(), annot=True, cmap='coolwarm', fmt='.2f')
plt.title('Correlation Heatmap')
plt.show()

# . Define features (X) and target (y)
# ---------------------------------------------------------------
categorical_cols = ["Nutrient", "Location", "Agro_Ecological_Zone", "SOIL_TYPE"]
numeric_cols = ["Rep", "Rate", "BY"]   # BY (Biomass Yield) is a strong predictor of GY

X = df[categorical_cols + numeric_cols]
y = df["GY"]

# 3. Build preprocessing + model pipeline
# ---------------------------------------------------------------
preprocessor = ColumnTransformer(
    transformers=[
        ("cat", OneHotEncoder(handle_unknown="ignore"), categorical_cols)
    ],
    remainder="passthrough"  # keep numeric columns as-is
)

rf_model = RandomForestRegressor(
    n_estimators=300,
    max_depth=None,
    min_samples_leaf=2,
    random_state=42,
    n_jobs=-1
)

pipeline = Pipeline(steps=[
    ("preprocessor", preprocessor),
    ("regressor", rf_model)
])

# 4. Train / Test split evaluation
# ---------------------------------------------------------------
X_train, X_test, y_train, y_test = train_test_split(
    X, y, test_size=0.2, random_state=42
)

pipeline.fit(X_train, y_train)
y_pred = pipeline.predict(X_test)

r2 = r2_score(y_test, y_pred)
rmse = mean_squared_error(y_test, y_pred) ** 0.5
mae = mean_absolute_error(y_test, y_pred)

print("\n=== Hold-out Test Set Performance ===")
print(f"R^2 Score : {r2:.4f}")
print(f"RMSE      : {rmse:.2f}")
print(f"MAE       : {mae:.2f}")

# 5. Cross-validation (5-fold)
# ---------------------------------------------------------------
kfold = KFold(n_splits=5, shuffle=True, random_state=42)
cv_scores = cross_val_score(pipeline, X, y, cv=kfold, scoring="r2")

print("\n=== 5-Fold Cross-Validation R^2 Scores ===")
print(np.round(cv_scores, 4))
print(f"Mean CV R^2 : {cv_scores.mean():.4f}")
print(f"Std  CV R^2 : {cv_scores.std():.4f}")
print(f"All folds positive: {bool((cv_scores > 0).all())}")

# 6. Feature importance
# ---------------------------------------------------------------
feature_names = pipeline.named_steps["preprocessor"].get_feature_names_out()
importances = pipeline.named_steps["regressor"].feature_importances_
feat_imp = pd.Series(importances, index=feature_names).sort_values(ascending=False)

print("\n=== Top 10 Feature Importances ===")
print(feat_imp.head(10))

import joblib

# 1. Save the model (or pipeline)
joblib.dump(pipeline, 'barley_rf_model.pkl')

# 2. Load the model back
loaded_model = joblib.load('barley_rf_model.pkl')

# 3. Use it to make predictions
predictions = loaded_model.predict(X_test)

from google.colab import files

# Download the saved model file directly to your local machine
files.download('barley_rf_model.pkl')